swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/SignUp"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/SignUpResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ProfileResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/Profile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ProfileResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for fetching all transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/{transaction_id}:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for fetching a transaction based on the ID
      parameters:
        - in: path
          name: transaction_id
          description: Transaction id
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    
    put:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions API
      description: API for updating transaction informations
      parameters:
        - in: path
          name: transaction_id
          description: Transaction id
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction informations
          required: true
          schema:
            $ref: "#/definitions/EditTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: User transaction infos updated successully
          schema:
            $ref: "#/definitions/EditTransactionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
        
  LoginResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          token:
            type: string
            
  SignUp:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  
  SignUpResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          password:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          createAt:
            type: string
          updateAt:
            type: string
  
  Profile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
        
  ProfileResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          email:
            type: string
          firstName:
            type: string
          lastName:
            type: string
          createAt:
            type: string
          updateAt:
            type: string
          id:
            type: string
  
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: transaction id
          date:
            type: string
            description: transaction date
          description:
            type: string
            description: transaction description
          amount:
            type: integer
            description: transaction amount
          category:
            type: string
            description: transaction category
          note:
            type: string
            description: transaction note
            
  TransactionObject:
    properties:
      id:
        type: string
        description: transaction id
      date:
        type: string
        description: transaction date
      description:
        type: string
        description: transaction description
      amount:
        type: string
        description: transaction amount
      note:
        type: string
        description: transaction note
      category:
        type: string
        description: transaction category
        
  TransactionApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: "#/definitions/TransactionObject"
          
  EditTransaction:
    type: object
    properties:
      notes:
        type: string
        description: transaction additional notes
      category:
        type: string
        description: transaction category
        
  EditTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: transaction id
          date:
            type: string
            description: transaction date
          description:
            type: string
            description: transaction description
          amount:
            type: integer
            description: transaction amount
          notes:
            type: string
            description: transaction additional notes
          category:
            type: string
            description: transaction category
      